import{a as q,S as P,i as s}from"./assets/vendor-Bt_EzQve.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const $="53042587-5c2e345549771b4d4f5e75931",B="https://pixabay.com/api/";async function m(n,r,o){const i={key:$,q:n,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:o};return(await q.get(B,{params:i})).data}const p=document.querySelector(".gallery"),f=document.querySelector(".loader"),y=document.querySelector(".load-more");let M=new P(".gallery a",{captionsData:"alt",captionDelay:250});function g(n){const r=n.map(({webformatURL:o,largeImageURL:i,tags:e,likes:t,views:a,comments:v,downloads:S})=>`
      <li class="gallery-item">
        <a href="${i}">
          <img src="${o}" alt="${e}" />
        </a>
        <div class="info">
          <p>Likes ${t}</p>
          <p>Views ${a}</p>
          <p>Comments ${v}</p>
          <p>Downloads ${S}</p>
        </div>
      </li>`).join("");p.insertAdjacentHTML("beforeend",r),M.refresh()}function E(){p.innerHTML=""}function L(){f.classList.remove("is-hidden")}function w(){f.classList.add("is-hidden")}function l(){y.classList.add("is-hidden")}function O(){y.classList.remove("is-hidden")}const b=document.querySelector(".form"),x=b.querySelector('input[name="search-text"]'),C=document.querySelector(".load-more"),h=document.querySelector(".gallery");let d="",c=1;const u=20;b.addEventListener("submit",async n=>{n.preventDefault();const r=x.value.trim();if(!r){s.warning({title:"Warning",message:"Please enter a search term!",position:"topRight"});return}d=r,c=1,E(),l(),L();try{const o=await m(d,c,u);if(o.hits.length===0){s.info({title:"Sorry",message:", there are no images matching your search query. Please try again!",position:"topRight"});return}g(o.hits),o.totalHits>u?O():(l(),s.info({message:"We're sorry, but you've reached the end of the search results.",position:"bottomCenter"}))}catch{s.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{w()}});C.addEventListener("click",async()=>{c+=1,L();try{const n=await m(c,u,d);g(n.hits);const{height:r}=h.firstElementChild.getBoundingClientRect();window.scrollBy({top:r*2,behaviour:"smooth"}),h.children.length>=n.totalHits&&(l(),s.info({message:"We're sorry, but you've reached the end of the search results.",position:"bottomCenter"}))}catch{s.error({title:"Error",message:"Somethimg went wrong. Please try again later.",position:"topRight"})}finally{w()}});
//# sourceMappingURL=index.js.map
