import{a as P,S as $,i as s}from"./assets/vendor-Bt_EzQve.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const B="53042587-5c2e345549771b4d4f5e75931",M="https://pixabay.com/api/";async function p(n,r,o){const i={key:B,q:n,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:o};return(await P.get(M,{params:i})).data}const f=document.querySelector(".gallery"),y=document.querySelector(".loader"),g=document.querySelector(".load-more");let E=new $(".gallery a",{captionsData:"alt",captionDelay:250});function L(n){const r=n.map(({webformatURL:o,largeImageURL:i,tags:e,likes:t,views:a,comments:S,downloads:q})=>`
      <li class="gallery-item">
        <a href="${i}">
          <img src="${o}" alt="${e}" />
        </a>
        <div class="info">
          <p>Likes ${t}</p>
          <p>Views ${a}</p>
          <p>Comments ${S}</p>
          <p>Downloads ${q}</p>
        </div>
      </li>`).join("");f.insertAdjacentHTML("beforeend",r),E.refresh()}function O(){f.innerHTML=""}function w(){y.classList.remove("is-hidden")}function b(){y.classList.add("is-hidden")}function c(){g.classList.add("is-hidden")}function d(){g.classList.remove("is-hidden")}const v=document.querySelector(".form"),x=v.querySelector('input[name="search-text"]'),C=document.querySelector(".load-more"),m=document.querySelector(".gallery");let u="",l=1;const h=20;v.addEventListener("submit",async n=>{n.preventDefault();const r=x.value.trim();if(!r){s.warning({title:"Warning",message:"Please enter a search term!",position:"topRight"});return}u=r,l=1,O(),c(),w();try{const o=await p(u,l,h);if(o.hits.length===0){s.info({title:"Sorry",message:"there are no images matching your search query. Please try again!",position:"topRight"});return}L(o.hits),o.totalHits>h?d():(c(),s.info({message:"We're sorry, but you've reached the end of the search results.",position:"bottomCenter"}))}catch{s.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{b()}});C.addEventListener("click",async()=>{l+=1,c(),w();try{const n=await p(u,l,h);L(n.hits),d();const{height:r}=m.firstElementChild.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"}),m.children.length>=n.totalHits?(c(),s.info({message:"We're sorry, but you've reached the end of the search results.",position:"bottomCenter"})):d()}catch{s.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{b()}});
//# sourceMappingURL=index.js.map
